targets:
  $default:
    sources:
      - swagger_input/**
      - $package$
      - lib/$lib$
      - lib/data/**
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: "swagger_input/"
          output_folder: "lib/generated/swagger_fireflyiii_api/"
          with_base_url: true
          separate_models: true
          override_equals_and_hashcode: false
          include_if_null: false
      drift_dev:
        enabled: true
        options:
          generate_connect_constructor: true
          use_data_class_name_for_companions: true
          store_date_time_values_as_text: false